#!/bin/bash

# Function to display headers
print_headers() {
  printf "%-15s" "Resource"
  # Show 'Namespace' column only for pods
  if [ "$RESOURCE_TYPE" == "pod" ]; then
    printf "%-15s" "Namespace"
  fi
  printf "%-60s" "Name"
  printf "%-15s" "CPU"
  printf "%-15s" "Memory"
  echo
}

# Function to get resource usage
resource_usage() {
  local RESOURCE_TYPE=$1
  local NAMESPACE=$2

  # Redirect the function's output to a variable using command substitution to sync output with headers
  USAGE=$(kubectl top "$RESOURCE_TYPE" -n "$NAMESPACE" | tail -n +2 | while read -r line
  do
    NAME=$(echo "$line" | awk '{print $1}')
    CPU=$(echo "$line" | awk '{print $2}')
    MEMORY=$(echo "$line" | awk '{print $3}')

    printf "%-15s" "$RESOURCE_TYPE"
    # Show 'Namespace' column only for pods
    if [ "$RESOURCE_TYPE" == "pod" ]; then
      printf "%-15s" "$NAMESPACE"
    fi
    printf "%-60s" "$NAME"
    printf "%-15s" "$CPU"
    printf "%-15s" "$MEMORY"
    echo
  done)  
}

# Main execution
# Check arguments
if { [ "$#" -eq 1 ] && [ "$1" = "-h" ]; } || { [ "$1" != "node" ] && [ "$1" != "pod" ]; }; then
  echo "Usage: kubectl usage [node|pod [<namespace>]]"
  exit 0
fi

RESOURCE_TYPE=$1
NAMESPACE="default" # Default namespace if not provided

if [ "$#" -eq 2 ]; then
  NAMESPACE=$2
fi

resource_usage "$RESOURCE_TYPE" "$NAMESPACE"
print_headers
echo "$USAGE"
